Repository jsk-ros-pkg/jsk_recognition, pull requests merged in 2018-05, with the labels that each got.

#2281 Fix for AssertionError in fast_rcnn.py
  jsk_perception/launch/fast_rcnn.launch
  jsk_perception/node_scripts/fast_rcnn.py
  jsk_perception/sample/sample_fast_rcnn.launch
  jsk_recognition_utils/python/jsk_recognition_utils/chainermodels/vgg16_fast_rcnn.py
  jsk_recognition_utils/python/jsk_recognition_utils/chainermodels/vgg_cnn_m_1024.py
Labels: bug, pkg/jsk_perception

#2278 Add documentation for installation of Chainer with GPU
  doc/index.rst
  doc/install_chainer_gpu.rst
Labels: document, enhancement

#2291 Fix warnings about <pcl/ros/conversions.h> and printf format
  jsk_pcl_ros/src/resize_points_publisher_nodelet.cpp
  jsk_pcl_ros/src/tilt_laser_listener_nodelet.cpp
Labels: enhancement

#2293 Update chainer_mask_rcnn to 0.3.0
  doc/jsk_perception/nodes/mask_rcnn_instance_segmentation.rst
  jsk_perception/node_scripts/mask_rcnn_instance_segmentation.py
  jsk_perception/sample/sample_mask_rcnn_instance_segmentation.launch
  jsk_perception/scripts/install_trained_data.py
Labels: enhancement

#2294 [jsk_perception] install config dir
  jsk_perception/CMakeLists.txt
Labels: enhancement
