Repository jsk-ros-pkg/jsk_recognition, pull requests merged in 2019-10, with the labels that each got.

#2454 Fix label_image_decomposer.py for Python3
  jsk_perception/node_scripts/label_image_decomposer.py
Labels: enhancement

#2410 MaskImageToDepthConsideredMaskImage: support approximate sync
  doc/jsk_pcl_ros_utils/nodes/mask_image_to_depth_considered_mask_image.md
  jsk_pcl_ros_utils/CMakeLists.txt
  jsk_pcl_ros_utils/cfg/MaskImageToDepthConsideredMaskImage.cfg
  jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/mask_image_to_depth_considered_mask_image.h
  jsk_pcl_ros_utils/sample/sample_mask_image_to_depth_considered_mask_image.launch
  jsk_pcl_ros_utils/src/mask_image_to_depth_considered_mask_image_nodelet.cpp
  jsk_pcl_ros_utils/test/mask_image_to_depth_considered_mask_image.test
Labels: PR/MergeOK, document, enhancement, pkg/jsk_pcl_ros_utils, sample, test

#2437 Publish human skelton msgs in OpenPose node
  doc/jsk_perception/nodes/people_pose_estimation_2d.rst
  jsk_perception/node_scripts/people_pose_estimation_2d.py
  jsk_perception/test/people_pose_estimation_2d.test
  jsk_recognition_msgs/CMakeLists.txt
  jsk_recognition_msgs/msg/HumanSkeleton.msg
  jsk_recognition_msgs/msg/HumanSkeletonArray.msg
Labels: feature

#2442 fix generate_readme.py and update readme
  .readme/gallery_checkerboard_detector.jpg
  .readme/gallery_jsk_pcl_ros.jpg
  .readme/gallery_jsk_pcl_ros_utils.jpg
  .readme/gallery_jsk_perception.jpg
  .readme/gallery_jsk_recognition_msgs.jpg
  .readme/gallery_jsk_recognition_utils.jpg
  .readme/gallery_resized_image_transport.jpg
  README.md
  checkerboard_detector/package.xml
  generate_readme.py
  imagesift/package.xml
  jsk_pcl_ros/package.xml
  jsk_pcl_ros_utils/package.xml
  jsk_perception/package.xml
  jsk_recognition_msgs/package.xml
  jsk_recognition_utils/package.xml
  resized_image_transport/package.xml
Labels: document

#2455 Fix label_id division by 256 -> 255
  jsk_perception/node_scripts/label_image_decomposer.py
Labels: bug

#2458 Fix Xtion2 Installation document
  doc/install_xtion2.rst
Labels: PR/MergeOK
