Repository jsk-ros-pkg/jsk_recognition, pull requests merged in 2021-01, with the labels that each got.

#2435 [jsk_perception] Support chainercv mask rcnn
  .travis.yml
  doc/jsk_perception/nodes/mask_rcnn_instance_segmentation.rst
  jsk_perception/node_scripts/mask_rcnn_instance_segmentation.py
  jsk_perception/package.xml
Labels: PR/MergeOK, document, enhancement, pkg/jsk_perception

#2566 [jsk_perception] do not exit if cupy is not installed
  jsk_perception/node_scripts/alexnet_object_recognition.py
  jsk_perception/node_scripts/deep_sort/deep_sort_tracker.py
  jsk_perception/node_scripts/deep_sort_tracker_node.py
  jsk_perception/node_scripts/face_pose_estimation.py
  jsk_perception/node_scripts/fast_rcnn.py
  jsk_perception/node_scripts/fcn_depth_prediction.py
  jsk_perception/node_scripts/fcn_object_segmentation.py
  jsk_perception/node_scripts/hmr/net.py
  jsk_perception/node_scripts/hmr/resnet_v2_50.py
  jsk_perception/node_scripts/hmr/smpl.py
  jsk_perception/node_scripts/human_mesh_recovery.py
  jsk_perception/node_scripts/mask_rcnn_instance_segmentation.py
  jsk_perception/node_scripts/openpose/hand_net.py
  jsk_perception/node_scripts/openpose/pose_net.py
  jsk_perception/node_scripts/people_pose_estimation_2d.py
  jsk_perception/node_scripts/regional_feature_based_object_recognition.py
  jsk_perception/node_scripts/ssd_object_detector.py
  jsk_perception/node_scripts/vgg16_object_recognition.py
  jsk_perception/scripts/create_db_for_feature_based_object_recognition.py
  jsk_perception/scripts/install_trained_data.py
  jsk_perception/scripts/ssd_train_dataset.py
  jsk_perception/scripts/train_fcn.py
  jsk_perception/scripts/train_fcn_depth_prediction.py
  jsk_perception/scripts/train_mask_rcnn.py
  jsk_perception/scripts/train_ssd.py
Labels: bug

#2568 [jsk_pcl_ros] remove wrong launch_manager in tabletop_object_detector.launch
  jsk_pcl_ros/sample/tabletop_object_detector.launch
Labels: bug

#2565 [jsk_recognition_utils] use try to import chainer depend modules
  jsk_recognition_utils/package.xml
  jsk_recognition_utils/python/jsk_recognition_utils/__init__.py
Labels: bug

#2563 add more debug info for virtual_camera_info
  jsk_perception/src/virtual_camera_mono.cpp
Labels: PR/MergeOK

#2558 support _image_transport:=compress for imagesift
  doc/imagesift/nodes/imagesift.rst
  imagesift/include/imagesift/imagesift.h
  imagesift/sample/imagesift_sample.launch
  imagesift/src/imagesift.cpp
Labels: PR/MergeOK
