Repository jsk-ros-pkg/jsk_recognition, pull requests merged in 2021-02, with the labels that each got.

#2540 update readme to add more badges
  .readme/gallery_jsk_recognition_utils.jpg
  README.md
Labels: PR/MergeOK, document

#2553 Add node to split image vertically and horizontally
  doc/jsk_perception/nodes/images/split_image.png
  doc/jsk_perception/nodes/split_image.md
  jsk_perception/CMakeLists.txt
  jsk_perception/node_scripts/split_image.py
  jsk_perception/sample/sample_split_image.launch
  jsk_perception/test/split_image.test
Labels: PR/MergeOK

#2557 Update depth_image_creator.md
  doc/jsk_pcl_ros/nodes/depth_image_creator.md
  jsk_pcl_ros/sample/sample_depth_image_creator.launch
  jsk_pcl_ros/src/depth_image_creator_nodelet.cpp
Labels: PR/MergeOK

#2561 migrate to travis-ci.com
  README.md
Labels: PR/MergeOK

#2539 [jsk_pcl_ros] support including tabletop_object_detector.launch file in any name space
  jsk_pcl_ros/sample/tabletop_object_detector.launch
Labels: PR/MergeOK, hacktoberfest-accepted, pkg/jsk_pcl_ros

#2562 [jsk_pcl_ros/line_segment_detector] LineList needs colors aligning with points
  jsk_pcl_ros/src/line_segment_detector_nodelet.cpp
Labels: PR/MergeOK

#2571 [jsk_pcl_ros] set larger min_size limit for organized multiplane segmentation
  jsk_pcl_ros/cfg/OrganizedMultiPlaneSegmentation.cfg
Labels: PR/PleaseFix, enhancement

#2551 add sample_plane_extraction.launch , plane_extraction.launch
  jsk_pcl_ros/launch/plane_extraction.launch
  jsk_pcl_ros/sample/rviz/plane_extraction.rviz
  jsk_pcl_ros/sample/sample_plane_extraction.launch
  jsk_pcl_ros/scripts/install_sample_data.py
Labels: PR/MergeOK

#2543 [DepthImageCreator] print more rosparm info on startup
  jsk_pcl_ros/src/depth_image_creator_nodelet.cpp
Labels: PR/MergeOK

#2538 Change default value of resolution_factor in DrawRects.cfg
  jsk_perception/cfg/DrawRects.cfg
Labels: PR/MergeOK, bug

#2476 [jsk_perception] apply_mask_image publish roi
  doc/jsk_perception/nodes/apply_mask_image.md
  jsk_perception/include/jsk_perception/apply_mask_image.h
  jsk_perception/src/apply_mask_image.cpp
Labels: PR/MergeOK, PR/WaitForMaintainerCheck, enhancement, pkg/jsk_perception

#2468 Add cluster point indices label filter
  doc/jsk_pcl_ros_utils/nodes/cluster_point_indices_label_filter.md
  doc/jsk_pcl_ros_utils/nodes/images/cluster_point_indices_label_filter.png
  jsk_pcl_ros_utils/CMakeLists.txt
  jsk_pcl_ros_utils/cfg/ClusterPointIndicesLabelFilter.cfg
  jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/cluster_point_indices_label_filter.h
  jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
  jsk_pcl_ros_utils/sample/sample_cluster_point_indices_label_filter.launch
  jsk_pcl_ros_utils/src/cluster_point_indices_label_filter_nodelet.cpp
  jsk_pcl_ros_utils/test/cluster_point_indices_label_filter.test
Labels: PR/MergeOK, enhancement, pkg/jsk_pcl_ros_utils

#2473 Add LabelArray to ssd object detector
  doc/jsk_perception/nodes/ssd_object_detector.md
  jsk_perception/node_scripts/ssd_object_detector.py
  jsk_perception/test/ssd_object_detector.test
Labels: PR/MergeOK, document, enhancement, pkg/jsk_perception, test

#2564 [jsk_pcl_ros] add z range option to heightmap converter
  doc/jsk_pcl_ros/nodes/heightmap_converter.md
  jsk_pcl_ros/cfg/HeightmapConverter.cfg
  jsk_pcl_ros/include/jsk_pcl_ros/heightmap_converter.h
  jsk_pcl_ros/src/heightmap_converter_nodelet.cpp
Labels: PR/PleaseFix
