Repository jsk-ros-pkg/jsk_recognition, pull requests merged in 2021-07, with the labels that each got.

#2604 [jsk_perception] update install_trained_data url
  jsk_perception/scripts/install_trained_data.py
Labels: PR/MergeOK, pkg/jsk_perception

#2586 Add python modules to enable sphinx_autobuild
  doc/requirements.txt
Labels: PR/MergeOK

#2577 [jsk_perception] add message size check to deep_sort_tracker_node.py
  jsk_perception/node_scripts/deep_sort_tracker_node.py
Labels: PR/MergeOK

#2527 Update the documentation for Intel RealSense
  doc/install_realsense_camera.rst
Labels: PR/MergeOK

#2579 [jsk_perception] support sensor_msgs/PanoramaInfo with adding a publisher to DualFisheyeToPanorama node
  jsk_perception/include/jsk_perception/dual_fisheye_to_panorama.h
  jsk_perception/src/dual_fisheye_to_panorama.cpp
  jsk_recognition_msgs/CMakeLists.txt
  jsk_recognition_msgs/msg/PanoramaInfo.msg
Labels: PR/MergeOK

#2598 add max_num and score_threshold param in bing
  doc/jsk_perception/nodes/bing.rst
  jsk_perception/include/jsk_perception/bing.h
  jsk_perception/sample/sample_bing.launch
  jsk_perception/src/bing.cpp
Labels: PR/MergeOK, pkg/jsk_perception

#2602 add OrganizedStatisticalOutlierRemoval
  doc/jsk_pcl_ros/nodes/images/organized_statistical_outlier_removal.png
  doc/jsk_pcl_ros/nodes/organized_statistical_outlier_removal.md
  jsk_pcl_ros/CMakeLists.txt
  jsk_pcl_ros/cfg/OrganizedStatisticalOutlierRemoval.cfg
  jsk_pcl_ros/include/jsk_pcl_ros/organized_statistical_outlier_removal.h
  jsk_pcl_ros/launch/organized_statistical_outlier_removal.launch
  jsk_pcl_ros/plugins/nodelet/libjsk_pcl_ros.xml
  jsk_pcl_ros/sample/include/play_rosbag_baxter_realsense_l515.xml
  jsk_pcl_ros/sample/rviz/organized_statistical_outlier_removal.rviz
  jsk_pcl_ros/sample/sample_organized_statistical_outlier_removal.launch
  jsk_pcl_ros/scripts/install_sample_data.py
  jsk_pcl_ros/src/organized_statistical_outlier_removal_nodelet.cpp
  jsk_pcl_ros/test/test_organized_statistical_outlier_removal.test
Labels: PR/MergeOK, pkg/jsk_pcl_ros

#2599 [jsk_pcl_ros] Stop tf when segmented cloud size is zero using cluster point indices decomposer
  jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
  jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
Labels: PR/MergeOK, pkg/jsk_pcl_ros

#2583 add aws_auto_checkin_app
  doc/jsk_perception/nodes/aws_auto_checkin_app.rst
  jsk_perception/node_scripts/aws_auto_checkin_app.py
  jsk_perception/sample/sample_aws_auto_checkin_app.launch
Labels: PR/MergeOK
