Repository jsk-ros-pkg/jsk_recognition, pull requests merged in 2021-09, with the labels that each got.

#2620 [WIP] [jsk_perception] add max_interval_duration for apply_mask_image
  jsk_perception/include/jsk_perception/apply_mask_image.h
  jsk_perception/src/apply_mask_image.cpp
Labels: enhancement

#2601 Add hand pose estimation
  doc/jsk_perception/nodes/hand_pose_estimation_2d.rst
  doc/jsk_perception/nodes/images/srhandnet.png
  jsk_perception/launch/hand_pose_estimation_2d.launch
  jsk_perception/node_scripts/hand_pose_estimation_2d.py
  jsk_perception/sample/include/play_rosbag_hand.xml
  jsk_perception/sample/sample_hand_pose_estimation_2d.launch
  jsk_perception/scripts/install_sample_data.py
  jsk_perception/scripts/install_trained_data.py
  jsk_perception/test/hand_pose_estimation_2d.test
  jsk_recognition_msgs/CMakeLists.txt
  jsk_recognition_msgs/msg/HandPose.msg
  jsk_recognition_msgs/msg/HandPoseArray.msg
Labels: PR/MergeOK, feature, pkg/jsk_perception

#2623 [jsk_perception] Add approximate sync true in sample mask rcnn instance segmentation
  jsk_perception/sample/sample_mask_rcnn_instance_segmentation.launch
Labels: PR/MergeOK

#2612 [WIP] add GPU/CUDA information on 18.04 / PyTorch
  doc/install_chainer_gpu.rst
Labels: PR/MergeOK

#2596 Enable to throttle insta360 image to reduce dual_fisheye_to_panorama CPU load
  jsk_perception/sample/sample_insta360_air.launch
Labels: PR/MergeOK

#2624 [jsk_perception] Add label_array_to_mask_image
  doc/jsk_perception/nodes/images/label_array_to_mask_image.png
  doc/jsk_perception/nodes/label_array_to_mask_image.rst
  jsk_perception/CMakeLists.txt
  jsk_perception/include/jsk_perception/label_array_to_mask_image.h
  jsk_perception/plugins/nodelet/libjsk_perception.xml
  jsk_perception/sample/include/play_rosbag_mask_rcnn_73b2_kitchen.xml
  jsk_perception/sample/sample_label_array_to_mask_image.launch
  jsk_perception/scripts/install_sample_data.py
  jsk_perception/src/label_array_to_mask_image.cpp
  jsk_perception/test/label_array_to_mask_image.test
Labels: PR/PleaseFix
