Repository jsk-ros-pkg/jsk_recognition, pull requests merged in 2023-11, with the labels that each got.

#2800 [jsk_perception] Support compressed type image in vil_inference_client.py
  jsk_perception/launch/classification.launch
  jsk_perception/launch/vqa.launch
  jsk_perception/src/jsk_perception/vil_inference_client.py
Labels: hacktoberfest-accepted

#2726 [jsk_perception] Add invert_mask_image nodelet
  doc/jsk_perception/nodes/images/invert_mask_image.jpg
  doc/jsk_perception/nodes/invert_mask_image.md
  jsk_perception/CMakeLists.txt
  jsk_perception/include/jsk_perception/invert_mask_image.h
  jsk_perception/plugins/nodelet/libjsk_perception.xml
  jsk_perception/sample/sample_invert_mask_image.launch
  jsk_perception/src/invert_mask_image.cpp
  jsk_perception/test/invert_mask_image.test
Labels: PR/MergeOK, document, test, sample, pkg/jsk_perception

#2744 Aws face update
  doc/jsk_perception/nodes/aws_auto_checkin_app.rst
  doc/jsk_perception/nodes/aws_detect_faces.rst
  jsk_perception/node_scripts/aws_auto_checkin_app.py
  jsk_perception/node_scripts/aws_detect_faces.py
  jsk_perception/node_scripts/draw_rects.py
  jsk_perception/sample/sample_aws_auto_checkin_app.launch
  jsk_perception/sample/sample_aws_detect_faces.launch
Labels: PR/MergeOK

#2766 [AWS] logdebug when detect face
  jsk_perception/node_scripts/aws_auto_checkin_app.py
  jsk_perception/node_scripts/aws_detect_faces.py
Labels: PR/waitForReview
