Repository jsk-ros-pkg/jsk_recognition, pull requests merged in 2023-10, with the labels that each got.

#2795 [doc] Add explanation of sending multiple questions in vqa_node
  doc/jsk_perception/nodes/classification_node.md
  doc/jsk_perception/nodes/vqa_node.md
Labels: document, hacktoberfest-accepted

#2794 [jsk_perception] Fix Cosine Similarity description in visualize string msg of classification_node
  jsk_perception/src/jsk_perception/vil_inference_client.py
Labels: hacktoberfest, hacktoberfest-accepted

#2801 [doc] Fix links to markdown format in install_chainer_gpu
  doc/install_chainer_gpu.md
Labels: hacktoberfest-accepted
