Repository jsk-ros-pkg/jsk_recognition, pull requests merged in 2025-05, with the labels that each got.

#2762 add depth_image_publisher package
  depth_image_publisher/CMakeLists.txt
  depth_image_publisher/README.md
  depth_image_publisher/cfg/DepthImagePublisher.cfg
  depth_image_publisher/nodelet_plugins.xml
  depth_image_publisher/package.xml
  depth_image_publisher/sample/sample_16uc1.png
  depth_image_publisher/sample/sample_32fc1.npz
  depth_image_publisher/src/node/depth_image_publisher.cpp
  depth_image_publisher/src/nodelet/depth_image_publisher_nodelet.cpp
  depth_image_publisher/test/depth_image_publisher.test
Labels: enhancement, PR/waitForReview

#2707 [jsk_perception/sample/apply_mask] Add clip and negative option for users
  jsk_perception/sample/sample_apply_mask_image.launch
Labels: enhancement, PR/MergeOK, pkg/jsk_perception

#2738 Set RULE_LAUNCH_COMPILE/LINK to ccache if CMAKE_VERSION < 3.4
  imagesift/CMakeLists.txt
  jsk_pcl_ros/CMakeLists.txt
  jsk_pcl_ros_utils/CMakeLists.txt
  jsk_perception/CMakeLists.txt
  jsk_recognition_utils/CMakeLists.txt
  resized_image_transport/CMakeLists.txt
Labels: PR/MergeOK
